[build]
  command = "cd apptolva_bitacora && bash build.sh"
  publish = "apptolva_bitacora"

[build.environment]
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/viewer"
  to = "/viewer.html"
  status = 200
